In [11]:
import torch

In [2]:
torch.__version__

'2.3.1+cu121'

tensor

In [3]:
torch.tensor(4)

tensor(4)

vector

In [4]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

Matrix

In [5]:
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]]
)

a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Column vector & Line vectors

In [6]:
torch.tensor([[1],[2],[3],[4]])

tensor([[1],
        [2],
        [3],
        [4]])

In [7]:
torch.tensor([1, 2, 3, 4])

tensor([1, 2, 3, 4])

nd- Tensor

In [8]:
torch.tensor([
    [[1, 2, 3],
     [2, 3, 4],
     [3, 4, 5]],

     [[2, 4, 6],
      [4, 6, 8],
      [6, 8, 10]],

    [[4, 8, 12],
     [8, 12, 16],
     [12, 16, 20]]
])

tensor([[[ 1,  2,  3],
         [ 2,  3,  4],
         [ 3,  4,  5]],

        [[ 2,  4,  6],
         [ 4,  6,  8],
         [ 6,  8, 10]],

        [[ 4,  8, 12],
         [ 8, 12, 16],
         [12, 16, 20]]])

data type

In [9]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([1.3, 2.1, 5])

In [12]:
a.dtype, b.dtype

(torch.int64, torch.float32)

In [13]:
c = torch.tensor([1, 2, 3], dtype=torch.uint8)
c

tensor([1, 2, 3])

In [14]:
c = c.type(torch.float16)
c

tensor([1., 2., 3.], dtype=torch.float16)

In [15]:
a.short()

tensor([1, 2, 3], dtype=torch.int16)

In [ ]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])